version: "3.8"

services:
  database:
    image: mysql:5.7 
    environment: 
      MYSQL_ROOT_PASSWORD: P204
      MYSQL_DATABASE: phonebook_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: Clarusway_1
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - clarusnet
    configs:
      - source: initialdb
      - target: /docker-entrypoint.initdb.d/init.sql

  app-server:
    image: "${ECR_REGISTRY}/${APP_REPO_NAME}:latest"
    deploy:
      mode: global
      update_config:
        parallelism: 2
        delay: 5s
        order: start-first
    port: "80:80"
    network:
      - clarusnet

network:
  clarusnet:
    driver: overlay

volume:
  db-data:

config:
  initialdb:
    file: ./init.sql

